### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for Triton

### ISSUE THREAD

**Issue by fadfhkdfga** [tritonmc/triton-website#51]
[Triton] Unhandled exception occurred in onPacketSending(PacketEvent) for Triton
java.lang.IllegalStateException: Unable to construct new instance using public net.minecraft.network.protocol.status.ServerPing$ServerData(java.lang.String,int)
        at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:21) ~[ProtocolLib-679.jar:?]

**Comment by diogotcorreia** [comment]
Hey
Please use the issue template for opening bug reports, this is missing a lot of information (including a longer stack trace, if available).

Regarding your issue, make sure you're using the latest ProtocolLib dev build.
